<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <IsPackable>true</IsPackable>
    <PackBuildOutput>false</PackBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="packages.lock.json"/>
  </ItemGroup>

  <PropertyGroup>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <NoWarn>NU5105</NoWarn>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Wcwidth\**\*.cs" Exclude="..\Wcwidth\obj\**\*" Link="External\Wcwidth\%(RecursiveDir)%(Filename)%(Extension)"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NuGetizer" PrivateAssets="All"/>
  </ItemGroup>

</Project>